### ISSUE TITLE
timezone issues

### ISSUE THREAD

**Issue by hiimivantang** [louixs/ubersicht_google_calendar#1]
My calendar timezone is +0800 and global calendar settings timezone is +0800 as well.
However, whole day event is still displayed across 2 days.

**Comment by louixs** [comment]
Hi @hiimivantang, thanks for pointing it out. I noticed the same issue recently on my calendar as well. Not sure why it suddenly broke. I'll have a look when I can. I'm also open for suggestions! 

Thanks

**Comment by louixs** [comment]
Hi again @hiimivantang, 

I've now pushed the changes that hopefully fixes the timezone issues. I tested with mine, my timezone is +0100 btw, and it worked. When you have a chance, could you try by getting the latest copy of this widget (https://github.com/louixs/ubersicht_google_calendar/raw/master/calendar.widget.zip) to see if it's fixed for you as well please?

Thanks

**Comment by louixs** [comment]
@hiimivantang, any luck?
