### ISSUE TITLE
Sorting by time is incorrect

### ISSUE THREAD

**Issue by spkane** [louixs/ubersicht_google_calendar#11]
The single digit hours are not zero padded, so they are not sorting correctly.

```
-- Today -----
All Day
10:30~11:30
11:30~12:00
13:00~14:00
8:00~8:25
8:30~9:30
```

**Comment by louixs** [comment]
You are 100% right. I'm planning to do a complete overhaul and refactor of the app as there are many issues. Again, a bit busy at the moment but I'll get to it as soon as I can! Thanks.
