### ISSUE TITLE
Issue with multiple displays

### ISSUE THREAD

**Issue by wicketlink** [louixs/ubersicht_google_calendar#9]
Multiple displays causes 3 distinct API key calls to happen, and the app will be broken on some of them. This may be a bug outside of the google calendar control and may roll all the way up to how ubersicht works?

**Comment by louixs** [comment]
@wicketlink I haven't tested with multiple displays yet. Does the same issue happen at all with any other widget though?

**Comment by wicketlink** [comment]
Yes! I actually just found the option in your widget though to limit it to
one display. You can close this.

**Comment by louixs** [comment]
Ah I see. Good to know that there's an option for that. Thanks!
